"""
Generate DDVQA-format JSON training data for Stages 2 & 3.

This converts our image folder dataset into the conversation format needed
by the LLM training pipeline:
  - Stage 2 (judge_only): Just real/fake classification
  - Stage 3 (full): Classification + multi-turn explanation

Usage:
    python finetune_aigen/generate_ddvqa_data.py \\
        --data_dir ./finetune_aigen/data/train \\
        --image_output_dir ./utils/DDVQA_images/aigen/train \\
        --output_judge ./utils/DDVQA_split/aigen/train_DDVQA_aigen_judge_only.json \\
        --output_full ./utils/DDVQA_split/aigen/train_DDVQA_aigen_full.json
"""

import os
import sys
import json
import shutil
import random
import argparse
from pathlib import Path
from tqdm import tqdm

# ============================================================================
# Explanation Templates for AI-Generated Images
# ============================================================================

# Templates for FAKE (AI-generated) images
FAKE_EXPLANATION_TEMPLATES = {
    "skin": [
        "The skin texture is unnaturally smooth and uniform, lacking natural pores and micro-details typical of real photographs.",
        "The skin appears overly airbrushed with an unnatural perfection that is characteristic of AI-generated images.",
        "There are subtle color gradients in the skin that do not follow natural lighting patterns.",
        "The skin lacks the natural imperfections, such as freckles, moles, or subtle blemishes, expected in a real photograph.",
        "The skin tone transitions are too smooth and lack the micro-variations seen in real skin under natural lighting.",
    ],
    "eyes": [
        "The eyes show subtle asymmetry in their reflections, which is a common artifact of AI image generation.",
        "The iris patterns appear unnaturally regular and lack the organic irregularities of real human eyes.",
        "The eye reflections do not match a consistent light source, suggesting AI generation.",
        "The pupils show slight deformations that are characteristic of diffusion model outputs.",
        "The eyes have an uncanny sharpness that differs from natural photograph quality.",
    ],
    "hair": [
        "The hair strands merge unnaturally in certain areas, a common artifact of AI-generated images.",
        "The hair boundary with the background shows blending artifacts typical of generative models.",
        "Individual hair strands lack the natural variation and randomness seen in real photographs.",
        "The hair texture appears repetitive in certain regions, suggesting pattern-based generation.",
    ],
    "face": [
        "The facial proportions show subtle inconsistencies that deviate from natural human anatomy.",
        "The overall facial structure appears too symmetrical and perfect, suggesting AI generation.",
        "There are subtle warping artifacts around the facial contours that indicate AI synthesis.",
        "The face has an overall plastic quality that differs from natural photographic renderings.",
    ],
    "background": [
        "The background contains blurred or inconsistent elements typical of AI-generated images.",
        "There are subtle structural inconsistencies in the background that suggest AI generation.",
        "The transition between the face and background shows characteristic AI generation artifacts.",
    ],
    "lighting": [
        "The lighting on the face does not correspond to a single consistent light source.",
        "Shadow patterns on the face are inconsistent with the apparent lighting direction.",
        "The overall illumination has an unnatural uniformity characteristic of AI-generated content.",
    ],
    "mouth": [
        "The teeth show subtle irregularities in alignment that are common in AI-generated faces.",
        "The mouth region has blending artifacts at the lip boundaries.",
        "The dental structure appears unnaturally perfect or has subtle rendering errors.",
    ],
    "general": [
        "This image appears to be fully generated by an artificial intelligence model. Multiple visual cues, including overly smooth textures, subtle inconsistencies in lighting, and characteristic generation artifacts, indicate this is not a real photograph.",
        "The image exhibits multiple hallmarks of AI generation, including unnatural skin texture, inconsistent micro-details, and subtle structural anomalies in facial features.",
        "Analysis reveals this image was likely produced by a generative AI model. The overall quality, while high, shows characteristic patterns of diffusion-based image synthesis.",
    ]
}

# Templates for REAL images
REAL_EXPLANATION_TEMPLATES = {
    "skin": [
        "The skin shows natural texture with visible pores and subtle imperfections consistent with a real photograph.",
        "Natural skin variations, including slight discolorations and texture details, are present and consistent with real photography.",
        "The skin exhibits natural micro-details and texture that are characteristic of genuine photographs.",
    ],
    "eyes": [
        "The eyes show consistent, natural reflections matching a real light source.",
        "The iris patterns show natural, organic irregularities consistent with real human eyes.",
    ],
    "hair": [
        "The hair shows natural variation and randomness in individual strands, consistent with a real photograph.",
        "Hair texture and boundaries appear natural with the irregular patterns expected in genuine photography.",
    ],
    "face": [
        "The facial features show natural proportions and subtle asymmetry characteristic of real human faces.",
        "The overall facial structure appears natural with the expected minor imperfections of a real face.",
    ],
    "general": [
        "The person has naturally detailed features with consistent lighting and textures throughout the image.",
        "This image shows characteristics consistent with genuine photography, including natural skin texture, consistent lighting, and organic facial details.",
        "The image displays natural photographic qualities with no obvious signs of AI generation.",
    ]
}

# Question templates (matching DDVQA style)
QUESTION_TEMPLATES_SINGLE = [
    "Describe the authenticity of the image based on {feature}.",
    "Analyze the {feature} in the image for signs of manipulation or AI generation.",
    "Examine the {feature} and determine if this image appears genuine.",
    "Based on the {feature}, assess whether this image is authentic.",
]

QUESTION_TEMPLATES_MULTI = [
    "Describe the authenticity of the image based on {features}.",
    "Analyze the {features} in the image for authenticity.",
    "Examine the {features} to assess if this image is real or AI-generated.",
]

QUESTION_TEMPLATES_GENERAL = [
    "Describe the authenticity of the image.",
    "Analyze this image for signs of AI generation.",
    "Assess whether this image appears to be genuine or AI-generated.",
    "Examine the visual characteristics of this image and determine its authenticity.",
]

JUDGMENT_QUESTIONS = [
    "Is the image real or fake?",
    "Do the image looks real or fake?",
    "Determine the authenticity. Is the image real or fake?",
]

JUDGMENT_RESPONSES_FAKE = [
    "Based on the learned representation, this image is fake.",
    "The image looks fake.",
    "This image appears to be AI-generated.",
]

JUDGMENT_RESPONSES_REAL = [
    "Based on the learned representation, this image is real.",
    "The image looks real.",
    "This image appears to be genuine.",
]


# ============================================================================
# Data Generation Functions
# ============================================================================

def generate_judge_only_entry(image_id: str, image_filename: str, is_fake: bool):
    """Generate a judge-only conversation (Stage 2 format)."""
    question = random.choice(JUDGMENT_QUESTIONS)
    
    if is_fake:
        answer = random.choice(JUDGMENT_RESPONSES_FAKE)
    else:
        answer = random.choice(JUDGMENT_RESPONSES_REAL)
    
    return {
        "id": image_id,
        "image": image_filename,
        "conversations": [
            {"from": "human", "value": f"<image>\n<deepfake>\n{question}"},
            {"from": "gpt", "value": answer}
        ]
    }


def generate_full_conversation_entry(image_id: str, image_filename: str, is_fake: bool):
    """Generate a full multi-turn conversation (Stage 3 format)."""
    templates = FAKE_EXPLANATION_TEMPLATES if is_fake else REAL_EXPLANATION_TEMPLATES
    
    # Decide conversation style
    style = random.choice(['single_feature', 'multi_feature', 'general', 'combined'])
    
    conversations = []
    
    if style == 'single_feature':
        feature = random.choice(list(templates.keys()))
        if feature == 'general':
            question = random.choice(QUESTION_TEMPLATES_GENERAL)
        else:
            question = random.choice(QUESTION_TEMPLATES_SINGLE).format(feature=feature)
        explanation = random.choice(templates[feature])
        judgment_q = random.choice(JUDGMENT_QUESTIONS)
        judgment_a = random.choice(JUDGMENT_RESPONSES_FAKE if is_fake else JUDGMENT_RESPONSES_REAL)
        
        conversations = [
            {"from": "human", "value": f"<image>\n<deepfake>\n{question}"},
            {"from": "gpt", "value": explanation},
            {"from": "human", "value": judgment_q},
            {"from": "gpt", "value": judgment_a}
        ]
    
    elif style == 'multi_feature':
        features = random.sample([k for k in templates.keys() if k != 'general'], 
                                min(3, len([k for k in templates.keys() if k != 'general'])))
        features_str = ", ".join(features)
        question = random.choice(QUESTION_TEMPLATES_MULTI).format(features=features_str)
        
        explanations = []
        for feat in features:
            explanations.append(random.choice(templates[feat]))
        explanation = " ".join(explanations)
        
        judgment_q = random.choice(JUDGMENT_QUESTIONS)
        judgment_a = random.choice(JUDGMENT_RESPONSES_FAKE if is_fake else JUDGMENT_RESPONSES_REAL)
        
        conversations = [
            {"from": "human", "value": f"<image>\n<deepfake>\n{question}"},
            {"from": "gpt", "value": explanation},
            {"from": "human", "value": judgment_q},
            {"from": "gpt", "value": judgment_a}
        ]
    
    elif style == 'general':
        question = random.choice(QUESTION_TEMPLATES_GENERAL)
        explanation = random.choice(templates.get('general', templates[list(templates.keys())[0]]))
        judgment_a = random.choice(JUDGMENT_RESPONSES_FAKE if is_fake else JUDGMENT_RESPONSES_REAL)
        
        conversations = [
            {"from": "human", "value": f"<image>\n<deepfake>\n{question} {random.choice(JUDGMENT_QUESTIONS)}"},
            {"from": "gpt", "value": f"{explanation} {judgment_a}"}
        ]
    
    else:  # combined
        question = random.choice(QUESTION_TEMPLATES_GENERAL)
        explanation = random.choice(templates.get('general', templates[list(templates.keys())[0]]))
        judgment_a = random.choice(JUDGMENT_RESPONSES_FAKE if is_fake else JUDGMENT_RESPONSES_REAL)
        
        conversations = [
            {"from": "human", "value": f"<image>\n<deepfake>\n{question}"},
            {"from": "gpt", "value": f"{explanation} {judgment_a}"}
        ]
    
    return {
        "id": image_id,
        "image": image_filename,
        "conversations": conversations
    }


def process_dataset(data_dir: str, image_output_dir: str, output_judge: str, output_full: str):
    """Process image folder dataset into DDVQA format JSON files."""
    
    os.makedirs(os.path.dirname(output_judge), exist_ok=True)
    os.makedirs(os.path.dirname(output_full), exist_ok=True)
    os.makedirs(image_output_dir, exist_ok=True)
    
    img_exts = {'.jpg', '.jpeg', '.png', '.bmp', '.webp'}
    
    judge_entries = []
    full_entries = []
    
    for label_name, is_fake in [('real', False), ('aigenerated', True)]:
        label_dir = os.path.join(data_dir, label_name)
        if not os.path.isdir(label_dir):
            print(f"  [WARN] Directory not found: {label_dir}")
            continue
        
        files = sorted([f for f in os.listdir(label_dir) if os.path.splitext(f)[1].lower() in img_exts])
        
        print(f"  Processing {len(files)} {label_name} images...")
        
        for f in tqdm(files, desc=f"  {label_name}"):
            # Create unique image ID
            stem = Path(f).stem
            prefix = "aigen" if is_fake else "real"
            image_id = f"{prefix}_{stem}"
            
            # Use a naming convention compatible with DDVQA
            # Fake images: 6_<id>.jpg (dataset_index=6 for AI-generated)
            # Real images: 7_<id>.jpg (dataset_index=7 for real-external)
            dataset_idx = 6 if is_fake else 7
            new_filename = f"{dataset_idx}_{stem}.jpg"
            
            # Copy/convert image to output directory
            src_path = os.path.join(label_dir, f)
            dst_path = os.path.join(image_output_dir, new_filename)
            if not os.path.exists(dst_path):
                try:
                    from PIL import Image
                    img = Image.open(src_path).convert('RGB')
                    img.save(dst_path, 'JPEG', quality=95)
                except Exception as e:
                    print(f"    [WARN] Failed to process {src_path}: {e}")
                    continue
            
            # Generate judge-only entry
            judge_entry = generate_judge_only_entry(image_id, new_filename, is_fake)
            judge_entries.append(judge_entry)
            
            # Generate full conversation entries (multiple per image for diversity)
            num_full = random.choice([1, 2, 3])
            for _ in range(num_full):
                full_entry = generate_full_conversation_entry(image_id, new_filename, is_fake)
                full_entries.append(full_entry)
    
    # Shuffle
    random.shuffle(judge_entries)
    random.shuffle(full_entries)
    
    # Save
    with open(output_judge, 'w') as f:
        json.dump(judge_entries, f, indent=2)
    
    with open(output_full, 'w') as f:
        json.dump(full_entries, f, indent=2)
    
    print(f"\n  [OK] Judge-only: {len(judge_entries)} entries -> {output_judge}")
    print(f"  [OK] Full conversation: {len(full_entries)} entries -> {output_full}")
    
    return judge_entries, full_entries


def generate_eval_data(data_dir: str, output_path: str):
    """Generate eval JSONL file in DDVQA eval format."""
    
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    img_exts = {'.jpg', '.jpeg', '.png', '.bmp', '.webp'}
    
    with open(output_path, 'w') as f_out:
        for label_name, is_fake in [('real', False), ('aigenerated', True)]:
            label_dir = os.path.join(data_dir, label_name)
            if not os.path.isdir(label_dir):
                continue
            
            files = sorted([fi for fi in os.listdir(label_dir) if os.path.splitext(fi)[1].lower() in img_exts])
            
            for fi in files:
                stem = Path(fi).stem
                dataset_idx = 6 if is_fake else 7
                
                # Detection question
                det_key = f"{dataset_idx}_{stem}_0"
                det_entry = {
                    det_key: {
                        "question": "Determine the authenticity. Is the image real or fake?",
                        "answer": ["The image looks fake." if is_fake else "The image looks real."],
                        "label": "fake" if is_fake else "real"
                    }
                }
                f_out.write(json.dumps(det_entry) + '\n')
                
                # Explanation question
                exp_key = f"{dataset_idx}_{stem}_1"
                question = random.choice(QUESTION_TEMPLATES_GENERAL)
                if is_fake:
                    answer = random.choice(FAKE_EXPLANATION_TEMPLATES['general'])
                else:
                    answer = random.choice(REAL_EXPLANATION_TEMPLATES['general'])
                
                exp_entry = {
                    exp_key: {
                        "question": question,
                        "answer": [answer],
                        "label": "fake" if is_fake else "real"
                    }
                }
                f_out.write(json.dumps(exp_entry) + '\n')
    
    print(f"  [OK] Eval data saved to: {output_path}")


def main():
    parser = argparse.ArgumentParser(description='Generate DDVQA-format data for AI-gen detection')
    parser.add_argument('--data_dir', type=str, default='./finetune_aigen/data/train',
                       help='Input image directory with real/ and aigenerated/ subfolders')
    parser.add_argument('--image_output_dir', type=str, default='./utils/DDVQA_images/aigen/train',
                       help='Output directory for processed images')
    parser.add_argument('--output_judge', type=str, 
                       default='./utils/DDVQA_split/aigen/train_DDVQA_aigen_judge_only.json',
                       help='Output path for judge-only JSON')
    parser.add_argument('--output_full', type=str,
                       default='./utils/DDVQA_split/aigen/train_DDVQA_aigen_full.json',
                       help='Output path for full conversation JSON')
    parser.add_argument('--eval_data_dir', type=str, default='./finetune_aigen/data/test',
                       help='Test data directory for eval format generation')
    parser.add_argument('--eval_output', type=str,
                       default='./utils/DDVQA_eval/aigen/test.jsonl',
                       help='Output path for eval JSONL')
    parser.add_argument('--seed', type=int, default=42, help='Random seed')
    
    args = parser.parse_args()
    random.seed(args.seed)
    
    print("=== Generating DDVQA-format Training Data ===\n")
    
    # Generate training data
    print("1. Processing training data...")
    judge_entries, full_entries = process_dataset(
        args.data_dir, args.image_output_dir,
        args.output_judge, args.output_full
    )
    
    # Generate eval data
    if os.path.isdir(args.eval_data_dir):
        print("\n2. Generating evaluation data...")
        generate_eval_data(args.eval_data_dir, args.eval_output)
    
    print("\n=== DDVQA Data Generation Complete ===")
    print(f"\nGenerated files:")
    print(f"  Judge-only (Stage 2): {args.output_judge} ({len(judge_entries)} entries)")
    print(f"  Full conv (Stage 3):  {args.output_full} ({len(full_entries)} entries)")
    print(f"  Images:               {args.image_output_dir}")
    if os.path.isdir(args.eval_data_dir):
        print(f"  Eval data:            {args.eval_output}")


if __name__ == '__main__':
    main()
